### PR TITLE
Changed sidebar to flexbox, search buttons not styled correctly

### PR DESCRIPTION
**Pull request by dzhang55**
screen shot 2017-04-16 at 4 34 29 pm

### CODE REVIEW

**Comment by katiejiang** [comment]
* Make sure that Report Incident and Address Search don't disappear in mobile view
* The red "x" button to close the incident form should be on the top right corner of the side panel

**Comment by katiejiang** [comment]
* Heading for "Filtering"
* Move CSV button to the bottom, possibly make it a different color?

**Comment by katiejiang** [comment]
Report Incident
Address Search

Filtering Divider
Bounding Boxes
Dates
Vehicle Type
License Plate

CSV Divider
Download
Upload

**Comment by katiejiang** [comment]
The start/end date calendars are now behind the map. I tried changing the z-index but that didn't work for me?

**Comment by dzhang55** [comment]
done with the changes! 
screen shot 2017-04-23 at 10 53 48 am
screen shot 2017-04-23 at 10 53 28 am
screen shot 2017-04-23 at 10 53 23 am

the calendar thing was an issue bc everything is now wrapped in a sidebar component, so it would just overflow and you'd have to scroll horizontally to see the calendar. i looked online and it seems like the simplest way to actually fix this is to set the calendar's position to fixed, but then its annoying to try and match it up with the date picker itself. so instead i just made it appear on the top of the input now so it fits into the sidebar

**Pull request merged**
