### PR TITLE
license filtering

### PR DESCRIPTION
**Pull request by dzhang55**
- styling looks okay on desktop and mobile, but i don't think the search was part of a mockup so idk if this is exactly what it should look like
- currently just does substring search, which seems fast enough for our fake data

### CODE REVIEW

**Comment by katiejiang** [comment]
A couple of comments:
* Could you convert everything to either uppercase or lowercase first for license plate filtering?
* Currently there's no way to clear the license plate filtering after something is typed into the search bar, other than to remove that text and hit search again (which some users might not think to do.) Any thoughts on how to fix this? If you want, you can maybe just add a button for "clear search"?
* I think we should hide the license plate search bar in the mobile view to free up the space on the screen though.
* The vehicle type filtering still appears in mobile view and is floating to the side; feel free to remove that.
* Could you move the report incident button to the top of the side bar in desktop view, and then let it stay where it is in the mobile view, but just a bit higher? It's really close to the bottom right now.

**Comment by dzhang55** [comment]
Addressed the first two comments:
- Now all license plates should be upper case when reports are submitted, and the search converts the query to uppercase as well.
- Whenever the text is cleared the search will refilter and show all the markers again.

I can work on the style changes in a separate PR with all the other style stuff!

**Comment by katiejiang** [comment]
The markers flash really quickly when I first type into the search bar; otherwise, this looks good to me. Feel free to merge after you pull from master!

**Comment by dzhang55** [comment]
ok cool i can show you next meeting what a fix for that looks like (it means that the filtering only clears once someone unfocuses the search input) but for now ill leave it as it is

**Pull request merged**
