### PR TITLE
Added calendar date filter

### PR DESCRIPTION
**Pull request by katiejiang**
Added Semantic UI Calendar date filtering

### CODE REVIEW

**Comment by sanjayss34** [comment]
The filter is not quite working for me - when I first filter out a particular marker and then I set the date so that the marker should reappear, it's not appearing for me.

**Comment by sanjayss34** [comment]
Also, it might be nice to prepopulate the starting and ending dates for all incidents when the page is loaded.

**Comment by sanjayss34** [comment]
screen shot 2017-03-13 at 4 49 17 pm
Do you know if you have any control over whether the calendar pop up is shown above or below the input box? I sometimes have the calendar in an inconvenient position as in the screenshot above. Aside from that minor styling issue, it looks good and ready to be merged!

**Comment by katiejiang** [comment]
Currently working on making filtering by date compatible with filtering by bounding boxes

**Comment by katiejiang** [comment]
Should be finished & ready to merge @sanjayss34

**Comment by sanjayss34** [comment]
Looks good to me, Katie!

**Pull request merged**
