### PR TITLE
Incident Model

### PR DESCRIPTION
**Pull request by nnarang7**
Added features for incident model

### CODE REVIEW

**Comment by katiejiang** [comment]
Quick q, does the model allow for multiple incident types? I think that in some incidents we could have pedestrian and bicyclist or bicyclist and automobile, rather than only pedestrian or only bicyclist.

**Comment by katiejiang** [comment]
Might be better to have a field for each type (pedestrian, automobile, bicycle) that is associated with a number.

**Comment by katiejiang** [comment]
Add contact name

**Comment by sanjayss34** [comment]
A few comments/questions:
1) Is incident.py still needed, since that model has been replaced by the incident model in incident_report.py? If not, please delete that.
2) You can delete the comments column from the model.
3) The injuries column should be optional.
4) There should be a column for the time of the incident in the model.

**Pull request merged**
