### PR TITLE
Natasha incident form

### PR DESCRIPTION
**Pull request by nnarang7**
Added a new form to report incidents instead of reports, haven't updated html to reflect the change but new incidents are being added to the database.

### CODE REVIEW

**Comment by sanjayss34** [comment]
I'm getting errors when I try to run the code due to the imports in app/main/views.py. Could you fix these and commit the changes?

**Comment by katiejiang** [comment]
Seems like just a small merge conflict that didn't get fixed in app/main/views.py!

**Comment by sanjayss34** [comment]
I tried removing that, but I still got an error because of an Agency import.

**Comment by katiejiang** [comment]
@nnarang7 I think right now the address is not working properly, so if you could take a look at that sometime this week that'd be great! Let us know if you have q's :)

**Pull request merged**
